# Generated by Django 6.1 on 2026-08-31 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public prayer wall'), ('LEADERS_ONLY', 'Leaders only')], default='LEADERS_ONLY', max_length=15)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending moderation'), ('APPROVED', 'Approved'), ('HIDDEN', 'Hidden'), ('ESCALATED', 'Escalated')], default='PENDING', max_length=15)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='prayer.prayerrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prayer_request', 'person'), name='unique_prayer_support')],
            },
        ),
    ]
