# Generated by Django 6.1 on 2026-08-31 08:38

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(default=datetime.time(21, 30))),
                ('quiet_hours_end', models.TimeField(default=datetime.time(7, 0))),
                ('category_overrides', models.JSONField(blank=True, default=dict)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('VOLUNTEER_REQUESTS', 'Volunteer Serving > Requests'), ('VOLUNTEER_REMINDERS', 'Volunteer Serving > Reminders'), ('VOLUNTEER_CHANGES', 'Volunteer Serving > Changes'), ('RIDES', 'Rides'), ('INBOX', 'Inbox'), ('EVENTS', 'Events'), ('FORMS', 'Forms & Consent'), ('PRAYER', 'Prayer'), ('GROUPS', 'Groups'), ('PROFILE', 'Profile'), ('LEADER_ATTENDANCE', 'Leadership > Attendance'), ('LEADER_ROSTER', 'Leadership > Roster'), ('LEADER_RIDES', 'Leadership > Rides'), ('LEADER_PRAYER', 'Leadership > Prayer'), ('LEADER_FOLLOWUP', 'Leadership > Follow-up'), ('LEADER_CMS', 'Leadership > CMS'), ('LEADER_DIGEST', 'Leadership > Weekly Summary')], max_length=30)),
                ('notification_type', models.CharField(choices=[('VOLUNTEER_ASSIGNMENT_REQUESTED', 'Volunteer assignment requested'), ('VOLUNTEER_RESPONSE_REMINDER', 'Volunteer response reminder'), ('VOLUNTEER_SERVING_SOON', 'Serving soon'), ('VOLUNTEER_SERVING_TODAY', 'Serving today'), ('VOLUNTEER_ASSIGNMENT_CHANGED', 'Assignment changed'), ('VOLUNTEER_ASSIGNMENT_CANCELLED', 'Assignment cancelled'), ('RIDE_STATUS_UPDATED', 'Ride status updated'), ('RIDE_CONFIRMED', 'Ride confirmed'), ('RIDE_CHANGED_CANCELLED', 'Ride changed/cancelled'), ('MESSAGE_RECEIVED', 'New direct message'), ('EVENT_ANNOUNCED', 'Event announced'), ('EVENT_REMINDER', 'Event reminder'), ('EVENT_CHANGED_CANCELLED', 'Event changed/cancelled'), ('FORM_ASSIGNED', 'Form assigned'), ('FORM_DUE_REMINDER', 'Form due reminder'), ('FORM_OVERDUE', 'Form overdue'), ('PRAYER_RESPONSE_AVAILABLE', 'Prayer response available'), ('GROUP_ADDED', 'Added to group'), ('GROUP_REMOVED', 'Removed from group'), ('PROFILE_ACTION_REQUIRED', 'Profile action required'), ('ATTENDANCE_RECONCILIATION_REMINDER', 'Attendance reconciliation reminder'), ('ATTENDANCE_NOT_CLOSED', 'Attendance session not closed'), ('ROSTER_DECLINED', 'Volunteer declined'), ('ROSTER_PENDING_SUMMARY', 'Pending roster responses'), ('ROSTER_UNFILLED_SUMMARY', 'Roster has unfilled positions'), ('RIDE_REQUEST_NEW', 'New ride request'), ('RIDE_UNASSIGNED_REMINDER', 'Ride request unassigned'), ('PRIVATE_PRAYER_NEW', 'New leaders-only prayer request'), ('PRAYER_ESCALATED', 'Prayer request escalated'), ('FOLLOWUP_DUE', 'Follow-up due soon'), ('FOLLOWUP_OVERDUE', 'Follow-up overdue'), ('CONTENT_PUBLISH_FAILED', 'Scheduled content failed to publish'), ('PUSH_CAMPAIGN_FAILED', 'Scheduled push failed'), ('WEEKLY_MINISTRY_SUMMARY', 'Weekly ministry summary')], max_length=50)),
                ('channel', models.CharField(choices=[('PUSH', 'Push'), ('EMAIL', 'Email')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('deep_link_type', models.CharField(blank=True, max_length=50)),
                ('deep_link_id', models.CharField(blank=True, max_length=64)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['person', 'read_at'], name='notificatio_person__250368_idx'), models.Index(fields=['status', 'scheduled_at'], name='notificatio_status_a9c93f_idx')],
            },
        ),
    ]
