# Generated by Django 6.1 on 2026-08-31 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience_everyone', models.BooleanField(default=True)),
                ('audience_school_years', models.JSONField(blank=True, default=list, help_text='e.g. [11, 12]')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('destination_type', models.CharField(choices=[('INTERNAL_SCREEN', 'Internal app screen'), ('EXTERNAL_URL', 'External URL'), ('EVENT', 'Event'), ('CONTENT', 'Content item'), ('GROUP', 'Group'), ('FORM', 'Form')], max_length=20)),
                ('destination_value', models.CharField(blank=True, help_text='URL or internal screen key', max_length=255)),
                ('destination_id', models.CharField(blank=True, help_text='PK of the Event/Content/Group/Form target', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('is_protected', models.BooleanField(default=False, help_text='Protected items cannot be deleted via the API.')),
                ('audience_groups', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_audience', to='groups.group')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
