# Generated by Django 6.1 on 2026-08-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('YOUTH', 'Youth'), ('LEADER', 'Leader'), ('ADMIN', 'Admin')], default='YOUTH', max_length=10),
        ),
    ]
