# Generated by Django 6.1 on 2026-08-31 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.URLField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('registration_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('audience_everyone', models.BooleanField(default=True)),
                ('audience_school_years', models.JSONField(blank=True, default=list, help_text='e.g. [11, 12]')),
                ('runsheet_url', models.URLField(blank=True)),
                ('runsheet_visibility', models.CharField(choices=[('SCHEDULED_VOLUNTEERS', 'Scheduled volunteers only'), ('ALL_VOLUNTEERS', 'All volunteers'), ('LEADERS_ONLY', 'Leaders only')], default='LEADERS_ONLY', max_length=25)),
                ('audience_groups', models.ManyToManyField(blank=True, related_name='targeted_events', to='groups.group')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
